# Generated by Django 3.1.2 on 2020-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201126_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='access_level',
            field=models.IntegerField(),
        ),
    ]
